version: "3.3"

services:
    mysql:
        image: mysql:5.7
        hostname: mysql
        volumes:
            - "./:/app"
        environment:
            MYSQL_DATABASE: highload
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3307:3306"
    php-fpm:
        image: webdevops/php-dev:7.3
        hostname: php-fpm
        volumes:
            - "./:/app"
        working_dir: "/app"
        depends_on:
            - mysql
    nginx:
        image: webdevops/nginx
        hostname: nginx
        environment:
            WEB_DOCUMENT_ROOT: /app/public
            WEB_DOCUMENT_INDEX: index.php
            WEB_PHP_SOCKET: php-fpm:9000
        ports:
            - "3001:80"
        volumes:
            - "./:/app"
        depends_on:
            - php-fpm
    grafana:
        image: grafana/grafana:7.3.6
        ports:
          - 3002:3000
    prometheus:
        image: prom/prometheus
        ports:
          - 9090:9090
        volumes:
          - ./docker/prometheus:/etc/prometheus
        command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml